apiVersion: v1
kind: Pod
metadata:
  name: iam-pod-metadata3
  labels:
    app: hello-there
spec:
  containers:
    - name: iam-a-affinity-pod3
      image: nginx
      imagePullPolicy: IfNotPresent
      
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: key1
                operator: In
                values:
                  - sdd
                  - fastram2

