apiVersion: batch/v1
kind: CronJob
metadata:
  name: i-am-a-pod

spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: iam-a-scheduler
    spec:
      template:
        spec:
          containers:
            - name: iam-a-container
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello From me!!! :)
          restartPolicy: OnFailure



