apiVersion: v1
kind: Service
metadata:
  name: credit-risk-service
spec:
  type: NodePort
  selector: 
    app: all-the-application-under-me
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080