apiVersion: v1
kind: Pod
metadata:
  name: nginx-tainted
  labels:
    app: nginx
spec:
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"
  containers:
    - name: nginxtainted
      image: nginx
      imagePullPolicy: IfNotPresent


